language: generic

services:
  - docker

before_install:
  - docker build -t ckddn9496/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true ckddn9496/react-test-app npm run test

after_success:
  - docker build -t ckddn9496/docker-frontend ./frontend
  - docker build -t ckddn9496/docker-backend ./backend
  - docker build -t ckddn9496/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push ckddn9496/docker-frontend
  - docker push ckddn9496/docker-backend
  - docker push ckddn9496/docker-nginx
