version: '3'
services: 

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true

  nginx:
  ####################### 재시작 정책 #######################
  # no : 어떠한 상황에서도 재시작을 하지 않는다
  # always : 항상
  # on-failure : on-failure 에러코드와 함께 컨테이너가 멈추었을때만 재시작
  # unless-stopped : 개발자가 임의로 멈추려고 할때를 제외하고 항상 재시작
    restart: always # 재시작 정책
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports: 
      - "3000:80"

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: app_backend
    volumes: 
      - /app/node_modules
      - ./backend:/app
    environment: 
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: ckddn9496
      MYSQL_DATABASE: myapp
      MYSQL_PORT: 3306

  # mysql:
  #   build: ./mysql
  #   restart: unless-stopped
  #   container_name: app_mysql
  #   ports: 
  #     - "3306:3306"
  #   volumes: 
  #     - ./mysql/mysql_data:/var/lib/mysql
  #     - ./mysql/sqls/:/docker-entrypoint-initdb.d/
  #   environment: 
  #     MYSQL_ROOT_PASSWORD: ckddn
  #     MYSQL_DATABASE: myapp